spring:
  profiles:
    default: develoment

features:
  configuration:
    file: features-development.yaml
    profile: development
---
spring:
  config:
    activate:
      on-profile: staging
features:
  configuration:
    file: features-staging.yaml
    profile: staging
server:
  port: 5000
---
spring:
  config:
    activate:
      on-profile: production
features:
  configuration:
    file: features-production.yaml
    profile: production
server:
  port: 5000
